
export default function motds() {
    return [
        "\"Hello, World!\"",
        "I'm currently looking for a job!",
        "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
        "A wood chuck would chuck as much wood as a wood chuck could chuck if a wood chuck could chuck wood.",
        "Learning WASM...",
        "stack overflow => ctrl + c => ctrl + v",
        "I'm a software developer, not a magician.",
        "Trans Rights !!",
        "I Hate Mondays",
        "Rust is Love, Rust is Life",
        "areeee teeeee effffff emmmmm",
        ":(){:|:&};:",
        "sudo rm -rf /* --no-preserve-root",
        "Hater of JS",
        "TypeScipt is just a bandaid",
        "I use Arch btw",
        "you gotta be crazy to use vim or emacs, this is why I use helix",
        "modal editing is the future",
        "DROP table Production;",
        "The only good ammount of JavaScript is no JavaScript",
        "Why use JS, when you can use Rust?",
        "U w U",
        "according to all known laws of aviation, there is no way a bee should be able to fly",
        "somebody once told me the world is gonna roll me",
        "me when css: (╯°□°)╯︵ ┻━┻",
        "It works on my machine ¯\\_(ツ)_/¯",
        "LGTM!! *pushes directly to prod*",
        "Ash, I told you to not push to main",
        "I'm not a robot",
        "404: Motd not found",
    ];
}